FROM cleanstart/node:latest-dev AS builder
USER root
WORKDIR /app
COPY app/package*.json ./
RUN npm install --omit=dev
COPY app/ ./
RUN mkdir -p /app/logs /app/tmp && chown -R 65532:65532 /app
USER 65532:65532

FROM cleanstart/node:latest
WORKDIR /app
COPY --from=builder --chown=65532:65532 /app /app
USER 65532:65532
EXPOSE 3000
CMD ["server.js"]